In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import style


In [2]:
# Quick peek at the dataset
df = pd.read_csv(r"C:\Users\BotchedPleb\OneDrive - Queens University of Charlotte\Documents\BIO_350_F25\Final_Project_BIO350\clean_individual_level_data_2021-01-10.csv")
df.head()

sample_id collect_date  age_yr  spikeod  spike_negod  spikeratio  spikepos  \
0  DBS-A0001    18-May-20      56    0.196        0.169    1.159763         0   
1  DBS-A0002    18-May-20      35    0.228        0.169    1.349112         0   
2  DBS-A0003    18-May-20      34    0.402        0.169    2.378698         1   
3  DBS-A0004    18-May-20      31    0.147        0.169    0.869823         0   
4  DBS-A0005    18-May-20      56    0.203        0.169    1.201183         0   

      rbtc   county                      vnrd  batch   sex       province  \
0  Mombasa  mombasa  Family_replacement_donor      1  male  coast_mombasa   
1  Mombasa  mombasa  Family_replacement_donor      1  male  coast_mombasa   
2  Mombasa  mombasa  Family_replacement_donor      1  male  coast_mombasa   
3  Mombasa  mombasa  Family_replacement_donor      1  male  coast_mombasa   
4  Mombasa  mombasa  Family_replacement_donor      1  male  coast_mombasa   

  age_category  period3  period10  
0     55-64yrs        1         2  
1     35-44yrs        1         2  
2     25-34yrs        1         2  
3     25-34yrs        1         2  
4     55-64yrs        1         2

In [3]:
# To double check for any possible null values in the already clean dataset
df.isnull().any()


sample_id       False
collect_date    False
age_yr          False
spikeod         False
spike_negod     False
spikeratio      False
spikepos        False
rbtc            False
county          False
vnrd            False
batch           False
sex             False
province        False
age_category    False
period3         False
period10        False
dtype: bool

In [4]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

In [5]:

# 1. Load Data
df = pd.read_csv(r"C:\Users\BotchedPleb\OneDrive - Queens University of Charlotte\Documents\BIO_350_F25\Final_Project_BIO350\clean_individual_level_data_2021-01-10.csv")

# 2. Features and Labels
X = df[['spikeod', 'spike_negod', 'spikeratio']]
y = df['spikepos']

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 4. Scale Features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 5. Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train_scaled, y_train)
y_pred_lr = log_reg.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("ROC-AUC:", roc_auc_score(y_test, log_reg.predict_proba(X_test_scaled)[:,1]))

# 6. Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, rf.predict_proba(X_test)[:,1]))

# 7. Confusion Matrix
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("Classification Report:\n", classification_report(y_test, y_pred_rf))


Logistic Regression Accuracy: 0.9979845482028888
ROC-AUC: 0.9999872152190034
Random Forest Accuracy: 0.9993281827342962
ROC-AUC: 1.0
Confusion Matrix:
 [[2716    2]
 [   0  259]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2718
           1       0.99      1.00      1.00       259

    accuracy                           1.00      2977
   macro avg       1.00      1.00      1.00      2977
weighted avg       1.00      1.00      1.00      2977



In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report

# Load in Data
df = pd.read_csv(r"C:\Users\BotchedPleb\OneDrive - Queens University of Charlotte\Documents\BIO_350_F25\Final_Project_BIO350\clean_individual_level_data_2021-01-10.csv")

# 1. Features and Labels
X = df[['spikeod', 'spike_negod', 'spikeratio']]
y = df['spikepos']

# 2. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 3. Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# -------------------------------
# Logistic Regression Comparison
# -------------------------------
log_reg_unscaled = LogisticRegression(max_iter=1000)
log_reg_unscaled.fit(X_train, y_train)
y_pred_lr_unscaled = log_reg_unscaled.predict(X_test)

log_reg_scaled = LogisticRegression(max_iter=1000)
log_reg_scaled.fit(X_train_scaled, y_train)
y_pred_lr_scaled = log_reg_scaled.predict(X_test_scaled)

print("=== Logistic Regression ===")
print(f"Unscaled Accuracy: {accuracy_score(y_test, y_pred_lr_unscaled):.4f}")
print(f"Unscaled ROC-AUC: {roc_auc_score(y_test, log_reg_unscaled.predict_proba(X_test)[:,1]):.4f}")
print(f"Scaled Accuracy: {accuracy_score(y_test, y_pred_lr_scaled):.4f}")
print(f"Scaled ROC-AUC: {roc_auc_score(y_test, log_reg_scaled.predict_proba(X_test_scaled)[:,1]):.4f}")

# -------------------------------
# Random Forest Comparison
# -------------------------------
rf_unscaled = RandomForestClassifier(n_estimators=100, random_state=42)
rf_unscaled.fit(X_train, y_train)
y_pred_rf_unscaled = rf_unscaled.predict(X_test)

rf_scaled = RandomForestClassifier(n_estimators=100, random_state=42)
rf_scaled.fit(X_train_scaled, y_train)
y_pred_rf_scaled = rf_scaled.predict(X_test_scaled)

print("\n=== Random Forest ===")
print(f"Unscaled Accuracy: {accuracy_score(y_test, y_pred_rf_unscaled):.4f}")
print(f"Unscaled ROC-AUC: {roc_auc_score(y_test, rf_unscaled.predict_proba(X_test)[:,1]):.4f}")
print(f"Scaled Accuracy: {accuracy_score(y_test, y_pred_rf_scaled):.4f}")
print(f"Scaled ROC-AUC: {roc_auc_score(y_test, rf_scaled.predict_proba(X_test_scaled)[:,1]):.4f}")



=== Logistic Regression ===
Unscaled Accuracy: 0.9990
Unscaled ROC-AUC: 1.0000
Scaled Accuracy: 0.9980
Scaled ROC-AUC: 1.0000

=== Random Forest ===
Unscaled Accuracy: 0.9993
Unscaled ROC-AUC: 1.0000
Scaled Accuracy: 0.9993
Scaled ROC-AUC: 1.0000


In [ ]:
# Adjusted Confusion Matrix
print("Confusion Matrix (Scaled):\n", confusion_matrix(y_test, y_pred_lr_scaled))
print("Classification Report:\n", classification_report(y_test, y_pred_lr_scaled))

print("Confusion Matrix (Unscaled):\n", confusion_matrix(y_test, y_pred_lr_unscaled))
print("Classification Report:\n", classification_report(y_test, y_pred_lr_unscaled))

Confusion Matrix (Scaled):
 [[2718    0]
 [   6  253]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2718
           1       1.00      0.98      0.99       259

    accuracy                           1.00      2977
   macro avg       1.00      0.99      0.99      2977
weighted avg       1.00      1.00      1.00      2977

Confusion Matrix (Unscaled):
 [[2718    0]
 [   3  256]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2718
           1       1.00      0.99      0.99       259

    accuracy                           1.00      2977
   macro avg       1.00      0.99      1.00      2977
weighted avg       1.00      1.00      1.00      2977

